---

# - name:           sros
#   include_tasks:  sros.yml
#   when: ansible_network_os == "sros"

- name:          "{{ ansible_network_os }}"
  include_tasks: "{{ ansible_network_os }}.yml"
  when: 
    - ansible_network_os is defined
